# -*- coding: utf-8 -*-
"""AI Code (Python).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZT0oGZ8zMgo9Jfoz9w4ItNOniwviRVqd
"""

import ast  # Import module to check code

def check_syntax(code):
    try:
        ast.parse(code)  # Try parsing or convert code for syntax errors
        return True, ""  # If Syntax correct then not show error message
    except SyntaxError as e:
        return False, f" Syntax Error : {e}"  # Returns The Name Of Error (Syntax)

def give_tips(code):
    tips = []  # Empty list for tips
    if "print(" in code:
        tips.append(" Used print() – consider f-strings too. ")
        # If print function used in code than text append to list of tips
    if "for " in code:
        tips.append(" Using for loop – check range usage. ")
        # If for loop in code than text append to list of tips
    if "while " in code:
        tips.append(" While loop used – avoid infinite loops. ")
        # If while loop in code than text append to list of tips
    if "if " in code:
        tips.append(" Conditional used – handle all possible cases. ")
        # If (if) in code than text append to list of tips
    if "def " in code:
        tips.append(" Function defined – add docstring explanations. ")
        # If user-defined function in code than text append to list of tips
    if not tips:
        tips.append(" Nice! Try loops or functions usage. ")
    return tips  # Return list that shows learning tips

def suggest_fix(error_msg):
    if "unexpected EOF" in error_msg:
        return " Check missing colon or closing bracket. "
    elif "EOL while scanning string literal" in error_msg:
        return " Check quotes in your string properly. "
    else:
        return " Check indentation and code carefully. "

print(" Welcome to AI Code Checker! ")  # Welcome the user nicely
print(" Paste code (type 'END' when finished) : ")  # Placeholder For User (Instructions)

user_code = ""  # empty string for code
while True:
    line = input()  # Read 1 line from user
    if line.strip().upper() == "END":  # Stop reading if END word is typed (Used upper() function for convert text into uppercase )
        break
    user_code += line + "\n"  # Append First line to full code

    valid, error_msg = check_syntax(user_code)  # Check the syntax of code

    if valid:
        print("\nNo syntax errors! Good job! ")  # If Syntax Is Correct
    else:
        print(f"\n{error_msg}")  # Show syntax error message
        fix = suggest_fix(error_msg)  # Suggest message for fixing the error
        print(f" Suggestion : {fix}")  # Print suggestion

tips = give_tips(user_code)  # Generate learning tips
print("\n Learning Tips : ")
for t in tips:
    print(f"- {t}")  # Print each tip using loop (for)

print(" \nThanks for using AI Code Checker! ")  # Ending message

